### ISSUE TITLE
Asking Questions

### ISSUE THREAD

**Issue by tc792617871** [wxiang7/pykylin#2]
NO1. click the tablename occurs the following errors in logs
ERROR:root:'NoneType' object has no attribute 'sqla_col'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/caravel/views.py", line 1183, in explore
    viz_obj.get_json(),
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 318, in get_json
    'data': self.get_data(),
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 448, in get_data
    df = self.get_df()
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 440, in get_df
    df = super(TableViz, self).get_df(query_obj)
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 165, in get_df
    self.results = self.datasource.query(**query_obj)
  File "/usr/local/lib/python2.7/site-packages/caravel/models.py", line 794, in query
    metrics_exprs = [metrics_dict.get(m).sqla_col for m in metrics]
No2. the project maybe not fit some datatypes in kylin ：like the type decimal(19,4) or timestamp(0)

**Comment by iandyilove** [comment]
yeah,I saw the same problem.
* File "/pyvenv/lib/python3.6/site-packages/pykylin-0.0.1-py3.6.egg/pykylin/dialect.py", line 172, in _map_column_type
    tpe = KYLIN_TYPE_MAP[tpe_NAME]
KeyError: 'DECIMAL(22, 7)'

but owner seems won't surpport the project.Hope he will continue it.superset and kylin are very good.
